# TCL File Generated by Component Editor 25.1
# Tue Sep 29 23:58:49 PDT 2026
# DO NOT MODIFY


# 
# led_animator "led_animator" v1.0
#  2026.09.29.23:58:49
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module led_animator
# 
set_module_property DESCRIPTION ""
set_module_property NAME led_animator
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "default group"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME led_animator
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL led_animator
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file led_animator.v VERILOG PATH rtl/peripheral/led_animator.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point led_external
# 
add_interface led_external conduit end
set_interface_property led_external associatedClock clock
set_interface_property led_external associatedReset reset
set_interface_property led_external ENABLED true
set_interface_property led_external EXPORT_OF ""
set_interface_property led_external PORT_NAME_MAP ""
set_interface_property led_external CMSIS_SVD_VARIABLES ""
set_interface_property led_external SVD_ADDRESS_GROUP ""

add_interface_port led_external led readdata Output 10

